// dev-packages/e2e-tests/test-applications/sveltekit-2/src/routes/+page.svelte
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<ul>
  <li>
    <a href="/client-error">Client error</a>
  </li>
  <li>
    <a href="/universal-load-error">Universal Load error</a>
  </li>
  <li>
    <a href="/server-load-error">Server Load error</a>
  </li>
  <li>
    <a href="/server-route-error">Server Route error</a>
  </li>
  <li>
    <a href="/users/123abc">Route with Params</a>
  </li>
  <li>
    <a href="/users">Route with Server Load</a>
  </li>
  <li>
    <a href="/universal-load-fetch">Route with fetch in universal load</a>
  </li>
</ul>

// dev-packages/e2e-tests/test-applications/solidstart/src/routes/index.tsx
import { A } from '@solidjs/router';

export default function Home() {
  return (
    <>
      <h1>Welcome to Solid Start</h1>
      <p>
        Visit <a href="https://docs.solidjs.com/solid-start">docs.solidjs.com/solid-start</a> to read the documentation
      </p>
      <ul>
        <li>
          <A href="/client-error">Client error</A>
        </li>
        <li>
          <A href="/server-error">Server error</A>
        </li>
        <li>
          <A id="navLink" href="/users/5">
            User 5
          </A>
        </li>
        <li>
          <A id="navLinkUserBack" href="/users/6">
            User 6
          </A>
        </li>
      </ul>
    </>
  );
}
